### ISSUE TITLE
Erro na execução do shell do DCDup

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/DCDup#2]
- Arquivo :

serverofi5:/bases/fiadmin2/DeDup/tpl $ ./01_Dedup_Indice.sh bbo iso-8859-1

- Chamada:

$DEDUP/Indice_GeraPipedFile_Sas.sh $DIRDATA/$1_pk $DIRDATA/in_indice_$1.txt

echo "Comando para check de DeDup"

echo "$DEDUP/WebDoubleCheckDuplicated.sh $DIRDATA/in_indice_$1.txt $2 http://serverofi5.bireme.br:8080/DeDup/services lilacs_Sas LILACS_Sas_Seven $DIRDATA/out1_indice_$1.txt

$DIRDATA/out2_indice_$1.txt $DIRDATA/out_ok_indice_$1.txt $2"

$DEDUP/WebDoubleCheckDuplicated.sh $DIRDATA/in_indice_$1.txt $2 http://serverofi5.bireme.br:8180/DeDup/services lilacs_Sas LILACS_Sas_Seven $DIRDATA/out1_indice_$1.txt

$DIRDATA/out2_indice_$1.txt $DIRDATA/out_ok_indice_$1.txt $2

- Mensagem de Erro:

Remote check
<<< 0
[error] (run-main-0) java.nio.charset.UnmappableCharacterException: Input length = 1
java.nio.charset.UnmappableCharacterException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:282)
        at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:285)
        at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
        at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
        at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
        at java.io.BufferedWriter.write(BufferedWriter.java:230)
        at java.io.Writer.write(Writer.java:157)
        at org.bireme.dcdup.WebDoubleCheckDuplicated.$anonfun$remoteCheck$1(WebDoubleCheckDuplicated.scala:205)
        at org.bireme.dcdup.WebDoubleCheckDuplicated.$anonfun$remoteCheck$1$adapted(WebDoubleCheckDuplicated.scala:200)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at org.bireme.dcdup.LineBatchIterator.foreach(LineBatchIterator.scala:24)
        at org.bireme.dcdup.WebDoubleCheckDuplicated.remoteCheck(WebDoubleCheckDuplicated.scala:200)
        at org.bireme.dcdup.WebDoubleCheckDuplicated.doubleCheck(WebDoubleCheckDuplicated.scala:98)
        at org.bireme.dcdup.WebDoubleCheckDuplicated$.delayedEndpoint$org$bireme$dcdup$WebDoubleCheckDuplicated$1(WebDoubleCheckDuplicated.scala:67)
        at org.bireme.dcdup.WebDoubleCheckDuplicated$delayedInit$body.apply(WebDoubleCheckDuplicated.scala:46)
        at scala.Function0.apply$mcV$sp(Function0.scala:34)
        at scala.Function0.apply$mcV$sp$(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at org.bireme.dcdup.WebDoubleCheckDuplicated$.main(WebDoubleCheckDuplicated.scala:46)
        at org.bireme.dcdup.WebDoubleCheckDuplicated.main(WebDoubleCheckDuplicated.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
[trace] Stack trace suppressed: run last compile:runMain for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:runMain for the full output.
[error] (compile:runMain) Nonzero exit code: 1
[error] Total time: 465 s, completed Sep 22, 2017 10:00:58 AM
/bases/fiadmin2/DeDup/tpl

Kátia

**Comment by heitorbarbieri** [comment]
Mesmo erro ocorrido do tíquete #4. Veja solução reportada nos comentários daquele tíquete.
