### ISSUE TITLE
Problema de checagem de duplicados no Scielo

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/DCDup#26]
Chama

/home/javaapps/sbt-projects/DCDup/sh/WebDoubleCheckDuplicated.sh -pipeFile=/bases/fiadmin2/DeDup/wrk/sci_201904/in_sci_201904_Sas.txt -pipeFileEncod=iso-8859-1 -dedupUrl=http://serverofi5.bireme.br:8180/DeDup/services -index=lilacs_Sas -schema=LILACS_Sas_Seven -outDupFile1=/bases/fiadmin2/DeDup/wrk/sci_201904/out1_sci_201904_Sas.txt -outDupFile2=/bases/fiadmin2/DeDup/wrk/sci_201904/out2_sci_201904_Sas.txt -outNoDupFile=/bases/fiadmin2/DeDup/wrk/sci_201904/out_ok_sci_201904_Sas.txt -outDupEncod=utf-8

Erro

Removing duplicated lines ... [error] java.lang.StringIndexOutOfBoundsException: String index out of range: 4
[error] at java.lang.String.substring(String.java:1963)
[error] at org.bireme.dcdup.CheckDuplicated$.getId(CheckDuplicated.scala:267)
[error] at org.bireme.dcdup.CheckDuplicated$.$anonfun$takeNoDuplicated$1(CheckDuplicated.scala:92)
[error] at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:160)
[error] at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:160)
[error] at scala.collection.Iterator.foreach(Iterator.scala:941)
[error] at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error] at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error] at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:160)
[error] at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:158)
[error] at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1429)
[error] at org.bireme.dcdup.CheckDuplicated$.takeNoDuplicated(CheckDuplicated.scala:87)
[error] at org.bireme.dcdup.WebDoubleCheckDuplicated.doubleCheck(WebDoubleCheckDuplicated.scala:116)
[error] at org.bireme.dcdup.WebDoubleCheckDuplicated$.delayedEndpoint$org$bireme$dcdup$WebDoubleCheckDuplicated$1(WebDoubleCheckDuplicated.scala:64)
[error] at org.bireme.dcdup.WebDoubleCheckDuplicated$delayedInit$body.apply(WebDoubleCheckDuplicated.scala:28)
[error] at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error] at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error] at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error] at scala.App.$anonfun$main$1$adapted(App.scala:80)
[error] at scala.collection.immutable.List.foreach(List.scala:392)
[error] at scala.App.main(App.scala:80)
[error] at scala.App.main$(App.scala:78)
[error] at org.bireme.dcdup.WebDoubleCheckDuplicated$.main(WebDoubleCheckDuplicated.scala:28)
[error] at org.bireme.dcdup.WebDoubleCheckDuplicated.main(WebDoubleCheckDuplicated.scala)
[error] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] at java.lang.reflect.Method.invoke(Method.java:498)
[error] (Compile / runMain) java.lang.StringIndexOutOfBoundsException: String index out of range: 4
[error] Total time: 62147 s, completed Apr 9, 2019 5:07:05 AM
/bases/fiadmin2/DeDup/scripts

**Comment by heitorbarbieri** [comment]
Fixed via commit 02c608f
