### ISSUE TITLE
Atualização do índice na serverofi5

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/DCDup#27]
Heitor, a atualização do índice na serverofi5 deu uma mensagem de Erro no Sas em inglês.

Comando:

cd /home/javaapps/sbt-projects/DCDup/sh

./MySQL2Lucene.sh osmio02.bireme.br acesso_fiadmin fi_admin@BIR fi_admin /home/javaapps/sbt-projects/DCDup/sql/LILACS_Sas.sql,/home/javaapps/sbt-projects/DCDup/sql/LILACS_Sas_ingles.sql http://dedup.bireme.org/services lilacs_Sas LILACS_Sas_Seven

Mensagem: 

<<< 16000
[error] java.io.IOException: ERROR: Lock held by this virtual machine: /home/javaapps/DeDup/work/lilacs_Sas/write.lock
[error]  at org.bireme.dcdup.WebPipe2Lucene$.optimizeIndex(WebPipe2Lucene.scala:163)
[error]  at org.bireme.dcdup.WebPipe2Lucene$.rsend(WebPipe2Lucene.scala:137)
[error]  at org.bireme.dcdup.WebPipe2Lucene$.$anonfun$convert$1(WebPipe2Lucene.scala:82)
[error]  at org.bireme.dcdup.WebPipe2Lucene$.$anonfun$convert$1$adapted(WebPipe2Lucene.scala:80)
[error]  at scala.collection.Iterator.foreach(Iterator.scala:941)
[error]  at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error]  at org.bireme.dcdup.LineBatchIterator.foreach(LineBatchIterator.scala:10)
[error]  at org.bireme.dcdup.WebPipe2Lucene$.convert(WebPipe2Lucene.scala:80)
[error]  at org.bireme.dcdup.WebPipe2Lucene$.delayedEndpoint$org$bireme$dcdup$WebPipe2Lucene$1(WebPipe2Lucene.scala:52)
[error]  at org.bireme.dcdup.WebPipe2Lucene$delayedInit$body.apply(WebPipe2Lucene.scala:25)
[error]  at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error]  at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error]  at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error]  at scala.App.$anonfun$main$1$adapted(App.scala:80)
[error]  at scala.collection.immutable.List.foreach(List.scala:392)
[error]  at scala.App.main(App.scala:80)
[error]  at scala.App.main$(App.scala:78)
[error]  at org.bireme.dcdup.WebPipe2Lucene$.main(WebPipe2Lucene.scala:25)
[error]  at org.bireme.dcdup.WebPipe2Lucene.main(WebPipe2Lucene.scala)
[error]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]  at java.lang.reflect.Method.invoke(Method.java:498)
[error] (Compile / runMain) java.io.IOException: ERROR: Lock held by this virtual machine: /home/javaapps/DeDup/work/lilacs_Sas/write.lock
[error] Total time: 230 s, completed Aug 12, 2019 9:52:28 AM
/home/javaapps/sbt-projects/DCDup/sh

**Comment by heitorbarbieri** [comment]
Commit 430bcb2
