### ISSUE TITLE
DCDup apresenta erro na execução

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/DCDup#28]
Running org.bireme.dcdup.DoubleCheckDuplicated -pipeFile=/bases/fiadmin2/DeDup/wrk/sci_201908/in_sci_201908_Sas.txt -pipeFileEncod=iso-8859-1 -index=/home/javaapps/DeDup/work/lilacs_Sas -confFile=/home/javaapps/DeDup/work/configLILACS_Sas_Seven.cfg -outDupFile1=/bases/fiadmin2/DeDup/wrk/sci_201908/out1_sci_201908_Sas.txt -outDupFile2=/bases/fiadmin2/DeDup/wrk/sci_201908/out2_sci_201908_Sas.txt -outNoDupFile=/bases/fiadmin2/DeDup/wrk/sci_201908/out_ok_sci_201908_Sas.txt -outDupEncod=utf-8
3+3+2+1+0
Creating temporary index ... >>> 100000
OK
[error] org.apache.lucene.store.LockObtainFailedException: Lock held by this virtual machine: /tmp/DCDup_1566216160544/write.lock
[error]  at org.apache.lucene.store.NativeFSLockFactory.obtainFSLock(NativeFSLockFactory.java:139)
[error]  at org.apache.lucene.store.FSLockFactory.obtainLock(FSLockFactory.java:41)
[error]  at org.apache.lucene.store.BaseDirectory.obtainLock(BaseDirectory.java:45)
[error]  at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:729)
[error]  at br.bireme.ngrams.NGIndex.getIndexWriter(NGIndex.java:101)
[error]  at br.bireme.ngrams.NGIndex.<init>(NGIndex.java:54)
[error]  at br.bireme.ngrams.NGIndex.<init>(NGIndex.java:36)
[error]  at org.bireme.dcdup.CheckDuplicated$.checkDuplicated(CheckDuplicated.scala:50)
[error]  at org.bireme.dcdup.DoubleCheckDuplicated$.doubleCheck(DoubleCheckDuplicated.scala:85)
[error]  at org.bireme.dcdup.DoubleCheckDuplicated$.delayedEndpoint$org$bireme$dcdup$DoubleCheckDuplicated$1(DoubleCheckDuplicated.scala:55)
[error]  at org.bireme.dcdup.DoubleCheckDuplicated$delayedInit$body.apply(DoubleCheckDuplicated.scala:20)
[error]  at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error]  at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error]  at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error]  at scala.App.$anonfun$main$1$adapted(App.scala:80)
[error]  at scala.collection.immutable.List.foreach(List.scala:392)
[error]  at scala.App.main(App.scala:80)
[error]  at scala.App.main$(App.scala:78)
[error]  at org.bireme.dcdup.DoubleCheckDuplicated$.main(DoubleCheckDuplicated.scala:20)
[error]  at org.bireme.dcdup.DoubleCheckDuplicated.main(DoubleCheckDuplicated.scala)
[error]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]  at java.lang.reflect.Method.invoke(Method.java:498)
[error] (Compile / runMain) org.apache.lucene.store.LockObtainFailedException: Lock held by this virtual machine: /tmp/DCDup_1566216160544/write.lock
[error] Total time: 30 s, completed Aug 19, 2019 9:03:07 AM
/bases/fiadmin2/DeDup/scripts

**Comment by heitorbarbieri** [comment]
Corrigido no issue cb48be1
