### ISSUE TITLE
Erro na importação dos documentos do MySQL no Lucene

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/DCDup#33]
/home/javaapps/sbt-projects/DCDup/sh

Sas

./MySQL2Lucene.sh osmio02.bireme.br acesso_fiadmin fi_admin@BIR fi_admin /home/javaapps/sbt-projects/DCDup/sql/LILACS_Sas.sql,/home/javaapps/sbt-projects/DCDup/sql/LILACS_Sas_ingles.sql http://dedup.bireme.org/services lilacs_Sas LILACS_Sas_Seven

+++400000
+++ All records converted!
Exception in thread "main" java.net.MalformedURLException: no protocol: LILACS_Sas_Seven
at java.net.URL.<init>(URL.java:593)
at java.net.URL.<init>(URL.java:490)
at java.net.URL.<init>(URL.java:439)
at scala.io.Source$.fromURL(Source.scala:134)
at scala.io.Source$.fromURL(Source.scala:129)
at org.bireme.dcdup.VerifyPipeFile$.checkRemote(CheckPipeFile.scala:167)
at org.bireme.dcdup.CheckPipeFile$.$anonfun$new$1(CheckPipeFile.scala:72)
at scala.util.Try$.apply(Try.scala:213)
at org.bireme.dcdup.CheckPipeFile$.delayedEndpoint$org$bireme$dcdup$CheckPipeFile$1(CheckPipeFile.scala:71)
at org.bireme.dcdup.CheckPipeFile$delayedInit$body.apply(CheckPipeFile.scala:29)
at scala.Function0.apply$mcV$sp(Function0.scala:39)
at scala.Function0.apply$mcV$sp$(Function0.scala:39)
at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
at scala.App.$anonfun$main$1$adapted(App.scala:80)
at scala.collection.immutable.List.foreach(List.scala:392)
at scala.App.main(App.scala:80)
at scala.App.main$(App.scala:78)
at org.bireme.dcdup.CheckPipeFile$.main(CheckPipeFile.scala:29)
at org.bireme.dcdup.CheckPipeFile.main(CheckPipeFile.scala)
Error: Could not find or load main class org.bireme.dcdup.WebPipe2Lucene
/home/javaapps/sbt-projects/DCDup/sh

**Comment by heitorbarbieri** [comment]
Implementado follow redirect. Url http está redirecionando para https. 
Corrigido em commit 29803cf
