### ISSUE TITLE
Erro de execução no DoubleCheckDuplicated.sh

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/DCDup#35]
Comando para check de DeDup Sas
/home/javaapps/sbt-projects/DCDup/sh/DoubleCheckDuplicated.sh -pipeFile=/bases/fiadmin2/DeDup/wrk/sci_201911/in_sci_201911_Sas.txt -pipeFileEncod=iso-8859-1 -index=/home/javaapps/DeDup/work/lilacs_Sas -confFile=/home/javaapps/DeDup/work/configLILACS_Sas_Seven.cfg -outDupFile1=/bases/fiadmin2/DeDup/wrk/sci_201911/out1_sci_201911_Sas.txt -outDupFile2=/bases/fiadmin2/DeDup/wrk/sci_201911/out2_sci_201911_Sas.txt -outNoDupFile1=/bases/fiadmin2/DeDup/wrk/sci_201911/out_ok_sci_201911_Sas.txt -outNoDupFile2=/bases/fiadmin2/DeDup/wrk/sci_201911/out_ok2_sci_201911_Sas.txt -outDupEncod=utf-8
Exception in thread "main" java.io.FileNotFoundException: -pipeFile=/bases/fiadmin2/DeDup/wrk/sci_201911/in_sci_201911_Sas.txt (No such file or directory)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(FileInputStream.java:195)
at java.io.FileInputStream.<init>(FileInputStream.java:138)
at scala.io.Source$.fromFile(Source.scala:94)
at scala.io.Source$.fromFile(Source.scala:79)
at scala.io.Source$.fromFile(Source.scala:57)
at org.bireme.dcdup.VerifyPipeFile$.checkLocal(CheckPipeFile.scala:130)
at org.bireme.dcdup.CheckPipeFile$.$anonfun$new$1(CheckPipeFile.scala:90)
at scala.util.Try$.apply(Try.scala:213)
at org.bireme.dcdup.CheckPipeFile$.delayedEndpoint$org$bireme$dcdup$CheckPipeFile$1(CheckPipeFile.scala:78)
at org.bireme.dcdup.CheckPipeFile$delayedInit$body.apply(CheckPipeFile.scala:29)
at scala.Function0.apply$mcV$sp(Function0.scala:39)
at scala.Function0.apply$mcV$sp$(Function0.scala:39)
at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
at scala.App.$anonfun$main$1$adapted(App.scala:80)
at scala.collection.immutable.List.foreach(List.scala:392)
at scala.App.main(App.scala:80)
at scala.App.main$(App.scala:78)
at org.bireme.dcdup.CheckPipeFile$.main(CheckPipeFile.scala:29)
at org.bireme.dcdup.CheckPipeFile.main(CheckPipeFile.scala)
==> Please, see the ignored documents at -pipeFile=/bases/fiadmin2/DeDup/wrk/sci_201911/in_sci_201911_Sas.txt.bad
3+3+2+1+0
Creating temporary index ... Exception in thread "main" java.nio.file.NoSuchFileException: /bases/fiadmin2/DeDup/wrk/sci_201911/in_sci_201911_Sas.txt.good
at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
at java.nio.file.Files.newByteChannel(Files.java:361)
at java.nio.file.Files.newByteChannel(Files.java:407)
at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
at java.nio.file.Files.newInputStream(Files.java:152)
at java.nio.file.Files.newBufferedReader(Files.java:2784)
at br.bireme.ngrams.NGrams.index(NGrams.java:140)
at org.bireme.dcdup.CheckDuplicated$.createTmpIndex(CheckDuplicated.scala:229)
at org.bireme.dcdup.CheckDuplicated$.$anonfun$checkDuplicated$1(CheckDuplicated.scala:49)
at scala.Option.getOrElse(Option.scala:189)
at org.bireme.dcdup.CheckDuplicated$.checkDuplicated(CheckDuplicated.scala:47)
at org.bireme.dcdup.DoubleCheckDuplicated$.doubleCheck(DoubleCheckDuplicated.scala:89)
at org.bireme.dcdup.DoubleCheckDuplicated$.delayedEndpoint$org$bireme$dcdup$DoubleCheckDuplicated$1(DoubleCheckDuplicated.scala:58)
at org.bireme.dcdup.DoubleCheckDuplicated$delayedInit$body.apply(DoubleCheckDuplicated.scala:22)
at scala.Function0.apply$mcV$sp(Function0.scala:39)
at scala.Function0.apply$mcV$sp$(Function0.scala:39)
at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
at scala.App.$anonfun$main$1$adapted(App.scala:80)
at scala.collection.immutable.List.foreach(List.scala:392)
at scala.App.main(App.scala:80)
at scala.App.main$(App.scala:78)
at org.bireme.dcdup.DoubleCheckDuplicated$.main(DoubleCheckDuplicated.scala:22)
at org.bireme.dcdup.DoubleCheckDuplicated.main(DoubleCheckDuplicated.scala)
/bases/fiadmin2/DeDup/scripts

**Comment by heitorbarbieri** [comment]
Não reprodutível na atual versão da biblioteca.
