### ISSUE TITLE
Erro ao executar o DoubleCheckDuplicated.sh 

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/DCDup#4]
Na primeira vez que executei o Check na nova estrutura de diretório.

G4 serverofi5:/bases/fiadmin2/DeDup/tpl $ ./01_Dedup_proc.sh test Sas iso-8859-1 http://serverofi5.bireme.br:8180/DeDup/services lilacs_Sas LILACS_Sas_Seven
[TIME-STAMP] 2017.10.04 16:25:46 [:INI:] Processa ./01_Dedup_proc.sh test Sas iso-8859-1 http://serverofi5.bireme.br:8180/DeDup/services

- Verificacoes iniciais
Gera Arquivo para checagem de Duplicacao!
Diretorio de processamento /home/javaapps/sbt-projects/DCDup/sh
Diretorio de trabalho e arquivo /bases/fiadmin2/DeDup/wrk/test/in_test.txt
Formato utilizado
pft=if v5.1='S' then s1:=(if p(v10) then (|//@//|+v10^*) else (|//@//|+v11^*) fi), s3:=(v30^*),(if p(v12) then 'LILACS_Sas|',v2[1],'|',replace(v12^*,'|',''),'|',s3,'|',v65[1].4,'|',v31[1],'|',v32[1]'|',s1,'|',if v14[1]^*>'' then v14[1]^* fi,/ fi),(if p(v13) then 'LILACS_Sas|',v2[1],'|',replace(v13^*,'|',''),'|',s3,'|',v65[1].4,'|',v31[1],'|',v32[1]'|',s1,'|',if v14[1]^*>'' then v14[1]^* fi,/ fi),fi
Comando para check de DeDup
/home/javaapps/sbt-projects/DCDup/sh/DoubleCheckDuplicated.sh /bases/fiadmin2/DeDup/wrk/test/in_test.txt iso-8859-1 http://serverofi5.bireme.br:8180/DeDup/services lilacs_Sas LILACS_Sas_Seven /bases/fiadmin2/DeDup/outs/test/out1_test.txt /bases/fiadmin2/DeDup/outs/test/out2_test.txt /bases/fiadmin2/DeDup/outs/test/out_ok_test.txt iso-8859-1
[info] Set current project to DCDup (in build file:/home/javaapps/sbt-projects/DCDup/)
[info] Updating {file:/home/javaapps/sbt-projects/DCDup/}root...
[info] Resolving jline#jline;2.14.4 ...
[info] Done updating.
[info] Compiling 10 Scala sources to /home/javaapps/sbt-projects/DCDup/target/scala-2.12/classes...
[warn] /home/javaapps/sbt-projects/DCDup/src/main/scala/org/bireme/dcdup/LineBatchIterator.scala:53: [MergeNestedIfs] These two nested ifs can be merged into one.
[warn]                           if (ignoreWhiteLines)
[warn]                           ^
[warn] /home/javaapps/sbt-projects/DCDup/src/main/scala/org/bireme/dcdup/WebDoubleCheckDuplicated.scala:309: [DuplicateIfBranches] If statement branches have the same structure.
[warn]           else if (allowSameId) set + (id1, id2)
[warn]                                     ^
[warn] two warnings found
[info] Running org.bireme.dcdup.WebDoubleCheckDuplicated /bases/fiadmin2/DeDup/wrk/test/in_test.txt iso-8859-1 http://serverofi5.bireme.br:8180/DeDup/services lilacs_Sas LILACS_Sas_Seven /bases/fiadmin2/DeDup/outs/test/out1_test.txt /bases/fiadmin2/DeDup/outs/test/out2_test.txt /bases/fiadmin2/DeDup/outs/test/out_ok_test.txt iso-8859-1

Self check
<<< 0

Remote check
<<< 0
[error] (run-main-0) java.nio.charset.UnmappableCharacterException: Input length = 1
java.nio.charset.UnmappableCharacterException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:282)
        at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:285)
        at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
        at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
        at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
        at java.io.BufferedWriter.write(BufferedWriter.java:230)
        at java.io.Writer.write(Writer.java:157)
        at org.bireme.dcdup.WebDoubleCheckDuplicated.$anonfun$remoteCheck$1(WebDoubleCheckDuplicated.scala:205)
        at org.bireme.dcdup.WebDoubleCheckDuplicated.$anonfun$remoteCheck$1$adapted(WebDoubleCheckDuplicated.scala:200)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at org.bireme.dcdup.LineBatchIterator.foreach(LineBatchIterator.scala:24)
        at org.bireme.dcdup.WebDoubleCheckDuplicated.remoteCheck(WebDoubleCheckDuplicated.scala:200)
        at org.bireme.dcdup.WebDoubleCheckDuplicated.doubleCheck(WebDoubleCheckDuplicated.scala:98)
        at org.bireme.dcdup.WebDoubleCheckDuplicated$.delayedEndpoint$org$bireme$dcdup$WebDoubleCheckDuplicated$1(WebDoubleCheckDuplicated.scala:67)
        at org.bireme.dcdup.WebDoubleCheckDuplicated$delayedInit$body.apply(WebDoubleCheckDuplicated.scala:46)
        at scala.Function0.apply$mcV$sp(Function0.scala:34)
        at scala.Function0.apply$mcV$sp$(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at org.bireme.dcdup.WebDoubleCheckDuplicated$.main(WebDoubleCheckDuplicated.scala:46)
        at org.bireme.dcdup.WebDoubleCheckDuplicated.main(WebDoubleCheckDuplicated.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
[trace] Stack trace suppressed: run last compile:runMain for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:runMain for the full output.
[error] (compile:runMain) Nonzero exit code: 1
[error] Total time: 256 s, completed Oct 4, 2017 4:30:07 PM
/bases/fiadmin2/DeDup/tpl

Fim de processamento

DURACAO DE PROCESSAMENTO
-------------------------------------------------------------------------
 - Inicio:  2017.10.04 16:25:46
 - Termino: 2017.10.04 16:30:07

 Tempo de execucao: 261 [s]
 Ou 0h 4m 21s

[TIME-STAMP] 2017.10.04 16:30:07 [:FIM:] Processa  ./01_Dedup_proc.sh test Sas iso-8859-1 http://serverofi5.bireme.br:8180/DeDup/services

**Comment by heitorbarbieri** [comment]
Quando documentos contendo caracteres estranhos armazenados no MySQL são utilizados para a geração do índice do DeDup, o processo de escrita dos documentos duplicados em um arquivo com encoding diferente de utf-8 gera um erro de mapeamento de caracteres.
A solução foi que ao escrever o arquivo de duplicados (com encoding diferente de utf-8), os caracteres estranhos foram substituídos pelo caracter de código 150.
