### ISSUE TITLE
Erro na atualização do índice do DeDup

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/DCDup#41]
Heitor, 
Por favor, você pode atualizar o índice do DeDup para o tipo SAS, infelizmente deu erro no final.

Comando 

./MySQL2Lucene.sh -host=osmio02.bireme.br -user=acesso_fiadmin -pswd=fi_admin@BIR -dbnm=fi_admin -sqls=/home/javaapps/sbt-projects/DCDup/sql/LILACS_Sas.sql,/home/javaapps/sbt-projects/DCDup/sql/LILACS_Sas_ingles.sql -dedupUrl=https://dedup.bireme.org/services -index=lilacs_Sas -schema=LILACS_Sas_Seven

<<< 1337000
<<< 1338000
Exception in thread "main" java.io.IOException: status code:500
        at org.bireme.dcdup.WebPipe2Lucene$.optimizeIndex(WebPipe2Lucene.scala:176)
        at org.bireme.dcdup.WebPipe2Lucene$.rsend(WebPipe2Lucene.scala:143)
        at org.bireme.dcdup.WebPipe2Lucene$.$anonfun$convert$1(WebPipe2Lucene.scala:81)
        at org.bireme.dcdup.WebPipe2Lucene$.$anonfun$convert$1$adapted(WebPipe2Lucene.scala:79)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
        at org.bireme.dcdup.LineBatchIterator.foreach(LineBatchIterator.scala:16)
        at org.bireme.dcdup.WebPipe2Lucene$.convert(WebPipe2Lucene.scala:79)
        at org.bireme.dcdup.WebPipe2Lucene$.delayedEndpoint$org$bireme$dcdup$WebPipe2Lucene$1(WebPipe2Lucene.scala:52)
        at org.bireme.dcdup.WebPipe2Lucene$delayedInit$body.apply(WebPipe2Lucene.scala:22)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1(App.scala:73)
        at scala.App.$anonfun$main$1$adapted(App.scala:73)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:920)
        at scala.App.main(App.scala:73)
        at scala.App.main$(App.scala:71)
        at org.bireme.dcdup.WebPipe2Lucene$.main(WebPipe2Lucene.scala:22)
        at org.bireme.dcdup.WebPipe2Lucene.main(WebPipe2Lucene.scala)
/home/javaapps/sbt-projects/DCDup/bin/remote

Grata

Katinha

**Comment by heitorbarbieri** [comment]
O problema descrito acima ocorre quando se tenta atualizar o índice do servidor de produção (modo remoto de atualização) que é o contrário do modo local quando se atualiza localmente o índice na serverofi5. 
Na atualização remota, garante-se que não haverá perda de entrada de dados novos no índice enquanto se faz a carga de um lote de documentos no mesmo, o custo disto é o tempo total de processamento que pode checar a 16 horas muitas vezes causando timeout de comunicação da aplicação.
Na atualização local o tempo de processamento é bem menor, menos de 4 horas, mas com o custo de se copiar o índice do servidor de produção para a serverofi5, atualizá-lo e perder alguns documentos novos entrados no servidor de produção e depois de se ter que copiar o índice atualizado de volta para o servidor de produção.
Optou-se, com o aval do @renatomurasaki,  que a atualização local é a melhor escolha pois existe a garantia de se concluir o processamento sem erros.
Com esta escolha, o erro supra citado deixa de ocorrer.
