### ISSUE TITLE
Erro na execução do check com o SciELO 

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/DCDup#5]
[error] (run-main-0) java.io.IOException: status code:502
java.io.IOException: status code:502
        at org.bireme.dcdup.WebDoubleCheckDuplicated.rcheck(WebDoubleCheckDuplicated.scala:240)
        at org.bireme.dcdup.WebDoubleCheckDuplicated.$anonfun$remoteCheck$1(WebDoubleCheckDuplicated.scala:202)
        at org.bireme.dcdup.WebDoubleCheckDuplicated.$anonfun$remoteCheck$1$adapted(WebDoubleCheckDuplicated.scala:200)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at org.bireme.dcdup.LineBatchIterator.foreach(LineBatchIterator.scala:24)
        at org.bireme.dcdup.WebDoubleCheckDuplicated.remoteCheck(WebDoubleCheckDuplicated.scala:200)
        at org.bireme.dcdup.WebDoubleCheckDuplicated.doubleCheck(WebDoubleCheckDuplicated.scala:98)
        at org.bireme.dcdup.WebDoubleCheckDuplicated$.delayedEndpoint$org$bireme$dcdup$WebDoubleCheckDuplicated$1(WebDoubleCheckDuplicated.scala:67)
        at org.bireme.dcdup.WebDoubleCheckDuplicated$delayedInit$body.apply(WebDoubleCheckDuplicated.scala:46)
        at scala.Function0.apply$mcV$sp(Function0.scala:34)
        at scala.Function0.apply$mcV$sp$(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at org.bireme.dcdup.WebDoubleCheckDuplicated$.main(WebDoubleCheckDuplicated.scala:46)
        at org.bireme.dcdup.WebDoubleCheckDuplicated.main(WebDoubleCheckDuplicated.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
[trace] Stack trace suppressed: run last compile:runMain for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:runMain for the full output.
[error] (compile:runMain) Nonzero exit code: 1
[error] Total time: 127504 s, completed Oct 4, 2017 8:11:53 PM
/bases/fiadmin2/DeDup/tpl

**Comment by heitorbarbieri** [comment]
@anakatiacamilo , por favor, passar a linha de chamada do shell para que eu possa reproduzir o erro. Obrigado.

**Comment by anakatiacamilo** [comment]
Executei novamente e o problema não aconteceu vou fechar o issue
